CatNews/config/routes.rb
CatNews::Application.routes.draw do
  root :to => "posts#index"

  get '/signin' => 'sessions#new' #REV: good, dont want to do this with a match.
  post '/signin' => 'sessions#create'
  match '/signout' => 'sessions#destroy'


  resources :comments, :except => [:edit, :update]
  resources :posts, :except => [:edit, :update] #REV: perhaps it makes sense to nest comments under posts?
  resources :users
  resources :emails, :except => [:edit, :update]
  #post '/user/add_karma'
end

CatNews/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  link       :string(255)
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  attr_accessible :link, :user_id, :comments_attributes

  belongs_to :user
  has_many :comments
  accepts_nested_attributes_for :comments
end

CatNews/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find_by_id(params[:id])
  end

  def new
    @post = Post.new
    @post.comments.build
    @user = current_user
  end

  def create
    @post = Post.new(params[:post])
    @post.user = current_user

    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def edit
    @post = Post.find_by_id(params[:id])
  end

  def update
    @post = Post.find_by_id(params[:id])
    if @post.update_attributes(params[:post])
    #REV: You can cut this down to just 'redirect_to @post'
      redirect_to user_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find_by_id(params[:id])
    @post.destroy
    redirect_to root_path
  end

end

CatNews/app/helpers/posts_helper.rb
module PostsHelper
end

CatNews/app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
<%= f.label :link %><br>
<%= f.text_field :link, :value => "http://" %><br>
<%= f.fields_for(:comments) do |comment_form| %>
  <%= comment_form.label :body, "First Comment:"%><br>
  <%= comment_form.text_area :body %><br>
<% end %>

<%= f.submit %>
<% end %>
<%= link_to "All Users", users_path %>

CatNews/app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

CatNews/app/views/posts/index.html.erb
<h1>Posts</h1>
<ul>
  <% @posts.each do |post| %>
  <li><%= link_to post.link, post_path(post) %></li>
  <% end %>
</ul>
<%= link_to "Create Post", new_post_path %>

CatNews/app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render partial: 'form' %>

CatNews/app/views/posts/show.html.erb
<h1>Post</h1>
<ul>
  <li>Link:  <%= link_to @post.link, @post.link %></li>
  <li>Comments:
    <ul>
      <% @post.comments.each do |comment| %>
        <li><%= comment.body %><% button_to "Upvote", %><li>
      <%end%>
    </ul>

</ul>
<%= link_to "Delete Post", post_path(@post), method: :delete%>
<!-- #show comments -->